USE SQL_DB;
-- Sort by salary (ascending)
SELECT * FROM OFFICE 
ORDER BY SALARY ;
-- Sort by salary (descending)
SELECT * FROM OFFICE 
ORDER BY SALARY DESC ;
-- Sort employee names alphabetically
SELECT EMPLOYEE_NAME FROM OFFICE 
ORDER BY EMPLOYEE_NAME ;
-- Reverse alphabetical order
SELECT EMPLOYEE_NAME FROM OFFICE 
ORDER BY EMPLOYEE_NAME DESC ;
-- Sort by age
SELECT * FROM OFFICE
ORDER BY AGE ;
-- Sort by joining date
SELECT * FROM OFFICE 
ORDER BY JOINING_DATE ;
-- IT employees sorted by salary
SELECT * FROM OFFICE WHERE DEPARTMENT = 'IT'
ORDER BY SALARY DESC ;
-- Multiple column sorting
SELECT EMPLOYEE_NAME , SALARY FROM OFFICE 
ORDER BY SALARY DESC , EMPLOYEE_NAME ASC ;
-- Sort by joining date (latest first)
SELECT EMPLOYEE_NAME , JOINING_DATE  FROM OFFICE 
ORDER BY JOINING_DATE DESC ;
-- Salary >= 40000 sorted ascending
SELECT EMPLOYEE_NAME , SALARY 
FROM OFFICE 
WHERE SALARY >= 40000 
ORDER BY SALARY ASC ;
