-- SQL Day 9 Practice
-- Topic: SELECT Statement
USE SQL_DB;
-- Display all records
SELECT * FROM OFFICE ;
-- Display employee names
SELECT EMPLOYEE_NAME FROM OFFICE ;
-- Display employee names and salary
SELECT EMPLOYEE_NAME , SALARY FROM OFFICE ;
-- -- Change column order
SELECT SALARY , EMPLOYEE_NAME FROM OFFICE ;
-- Alias
SELECT EMPLOYEE_NAME AS NAME FROM OFFICE ;

SELECT SALARY AS MONTHLY_SALARY FROM OFFICE ;
-- calculations
SELECT EMPLOYEE_NAME , SALARY + 5000 AS NEW_SALARY FROM OFFICE;

SELECT EMPLOYEE_NAME , SALARY * 12 AS ANNUAL_SALARY FROM OFFICE ;
-- Display unique departments
SELECT DISTINCT DEPARTMENT FROM OFFICE ;


