-- Day 5 SQL Learning

-- Super Key:
-- Any column or combination of columns that can uniquely identify a row.

-- Candidate Key:
-- A minimal unique identifier without unnecessary columns.

-- Unique Key:
-- Prevents duplicate values in a column.

-- Natural Key:
-- A real-world meaningful identifier.
-- Example: Email, Aadhaar Number, Passport Number.

-- Surrogate Key:
-- An artificial key generated by the database.
-- Example: StudentID, UserID.

-- Example:

-- StudentID | Email              | Name
-- 101       | varsha@gmail.com   | Varsha
-- 102       | rahul@gmail.com    | Rahul

-- Candidate Keys:
-- StudentID
-- Email

-- Super Keys:
-- StudentID
-- Email
-- StudentID + Name
-- Email + Name

-- Natural Key:
-- Email

-- Surrogate Key:
-- StudentID